<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Web Service Description for MOA SP/SS 1.4
-->
<definitions name="MOA" targetNamespace="http://reference.e-government.gv.at/namespace/moa/20020822#" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://reference.e-government.gv.at/namespace/moa/20020822#" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:moa="http://reference.e-government.gv.at/namespace/moa/20020822#" xmlns:xsd="http://www.w3.org/1999/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <import namespace="http://reference.e-government.gv.at/namespace/moa/20020822#" location="MOA-SPSS-1.3.xsd"/>
  <message name="VerifyCMSSignatureInput">
    <part name="body" element="moa:VerifyCMSSignatureRequest"/>
  </message>
  <message name="VerifyCMSSignatureOutput">
    <part name="body" element="moa:VerifyCMSSignatureResponse"/>
  </message>
  <message name="MOAFault">
    <part name="body" element="moa:ErrorResponse"/>
  </message>
  <portType name="SignatureVerificationPortType">
    <operation name="verifyCMSSignature">
      <input message="tns:VerifyCMSSignatureInput"/>
      <output message="tns:VerifyCMSSignatureOutput"/>
      <fault name="MOAFault" message="tns:MOAFault"/>
    </operation>
  </portType>
  <binding name="SignatureVerificationBinding" type="tns:SignatureVerificationPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="verifyCMSSignature">
      <soap:operation soapAction="urn:VerifyCMSSignatureAction"/>
      <input>
        <soap:body use="literal" namespace="http://reference.e-government.gv.at/namespace/moa/20020822#"/>
      </input>
      <output>
        <soap:body use="literal" namespace="http://reference.e-government.gv.at/namespace/moa/20020822#"/>
      </output>
      <fault name="MOAFault">
        <soap:fault use="literal" namespace="http://reference.e-government.gv.at/namespace/moa/20020822#"/>
      </fault>
    </operation>
  </binding>
  <service name="SignatureVerificationService">
    <port name="SignatureVerificationPort" binding="tns:SignatureVerificationBinding">
      <!--
        Please note that the location URL must be adapted to the actual service URL.
      <soap:address location="http://localhost/moa-spss/services/SignatureVerification"/>
      -->
    </port>
  </service>
</definitions>
