//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.05 at 04:21:33 PM CET 
//


package at.gv.egiz.sl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InfoboxReadResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InfoboxReadResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="BinaryFileData" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}Base64XMLContentType"/>
 *         &lt;element name="AssocArrayData" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}InfoboxReadDataAssocArrayType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfoboxReadResponseType", propOrder = {
    "binaryFileData",
    "assocArrayData"
})
@XmlRootElement
public class InfoboxReadResponseType {

    @XmlElement(name = "BinaryFileData")
    protected Base64XMLContentType binaryFileData;
    @XmlElement(name = "AssocArrayData")
    protected InfoboxReadDataAssocArrayType assocArrayData;

    /**
     * Gets the value of the binaryFileData property.
     * 
     * @return
     *     possible object is
     *     {@link Base64XMLContentType }
     *     
     */
    public Base64XMLContentType getBinaryFileData() {
        return binaryFileData;
    }

    /**
     * Sets the value of the binaryFileData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Base64XMLContentType }
     *     
     */
    public void setBinaryFileData(Base64XMLContentType value) {
        this.binaryFileData = value;
    }

    /**
     * Gets the value of the assocArrayData property.
     * 
     * @return
     *     possible object is
     *     {@link InfoboxReadDataAssocArrayType }
     *     
     */
    public InfoboxReadDataAssocArrayType getAssocArrayData() {
        return assocArrayData;
    }

    /**
     * Sets the value of the assocArrayData property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfoboxReadDataAssocArrayType }
     *     
     */
    public void setAssocArrayData(InfoboxReadDataAssocArrayType value) {
        this.assocArrayData = value;
    }

}
