//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 04:01:10 PM CEST 
//


package at.gv.egiz.sl.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DecryptCMSRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DecryptCMSRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CMSMessage" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="EncryptedContent" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}CMSEncryptedContentType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ReturnResult" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}ReturnResultType" default="xml" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DecryptCMSRequestType", propOrder = {
    "cmsMessage",
    "encryptedContent"
})
public class DecryptCMSRequestType {

    @XmlElement(name = "CMSMessage", required = true)
    protected byte[] cmsMessage;
    @XmlElement(name = "EncryptedContent")
    protected CMSEncryptedContentType encryptedContent;
    @XmlAttribute(name = "ReturnResult")
    protected ReturnResultType returnResult;

    /**
     * Gets the value of the cmsMessage property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCMSMessage() {
        return cmsMessage;
    }

    /**
     * Sets the value of the cmsMessage property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCMSMessage(byte[] value) {
        this.cmsMessage = value;
    }

    /**
     * Gets the value of the encryptedContent property.
     * 
     * @return
     *     possible object is
     *     {@link CMSEncryptedContentType }
     *     
     */
    public CMSEncryptedContentType getEncryptedContent() {
        return encryptedContent;
    }

    /**
     * Sets the value of the encryptedContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CMSEncryptedContentType }
     *     
     */
    public void setEncryptedContent(CMSEncryptedContentType value) {
        this.encryptedContent = value;
    }

    /**
     * Gets the value of the returnResult property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnResultType }
     *     
     */
    public ReturnResultType getReturnResult() {
        if (returnResult == null) {
            return ReturnResultType.XML;
        } else {
            return returnResult;
        }
    }

    /**
     * Sets the value of the returnResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnResultType }
     *     
     */
    public void setReturnResult(ReturnResultType value) {
        this.returnResult = value;
    }

}
