//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 04:01:10 PM CEST 
//


package at.gv.egiz.sl.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EncryptXMLRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EncryptXMLRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RecipientPublicKey" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}XMLRecipientPublicKeyType" maxOccurs="unbounded"/>
 *         &lt;element name="ToBeEncrypted" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}ToBeEncryptedType" maxOccurs="unbounded"/>
 *         &lt;element name="EncryptionInfo" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}EncryptionInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EncryptXMLRequestType", propOrder = {
    "recipientPublicKey",
    "toBeEncrypted",
    "encryptionInfo"
})
@XmlSeeAlso({
    EncryptXMLRequest.class
})
public class EncryptXMLRequestType {

    @XmlElement(name = "RecipientPublicKey", required = true)
    protected List<XMLRecipientPublicKeyType> recipientPublicKey;
    @XmlElement(name = "ToBeEncrypted", required = true)
    protected List<ToBeEncryptedType> toBeEncrypted;
    @XmlElement(name = "EncryptionInfo")
    protected EncryptionInfoType encryptionInfo;

    /**
     * Gets the value of the recipientPublicKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recipientPublicKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecipientPublicKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLRecipientPublicKeyType }
     * 
     * 
     */
    public List<XMLRecipientPublicKeyType> getRecipientPublicKey() {
        if (recipientPublicKey == null) {
            recipientPublicKey = new ArrayList<XMLRecipientPublicKeyType>();
        }
        return this.recipientPublicKey;
    }

    /**
     * Gets the value of the toBeEncrypted property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the toBeEncrypted property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getToBeEncrypted().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ToBeEncryptedType }
     * 
     * 
     */
    public List<ToBeEncryptedType> getToBeEncrypted() {
        if (toBeEncrypted == null) {
            toBeEncrypted = new ArrayList<ToBeEncryptedType>();
        }
        return this.toBeEncrypted;
    }

    /**
     * Gets the value of the encryptionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link EncryptionInfoType }
     *     
     */
    public EncryptionInfoType getEncryptionInfo() {
        return encryptionInfo;
    }

    /**
     * Sets the value of the encryptionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncryptionInfoType }
     *     
     */
    public void setEncryptionInfo(EncryptionInfoType value) {
        this.encryptionInfo = value;
    }

}
