//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 04:01:10 PM CEST 
//


package at.gv.egiz.sl.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EncryptCMSRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EncryptCMSRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RecipientPublicKey" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}CMSRecipientPublicKeyType" maxOccurs="unbounded"/>
 *         &lt;element name="ToBeEncrypted" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}CMSToBeEncryptedType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ReturnBinaryResult" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EncryptCMSRequestType", propOrder = {
    "recipientPublicKey",
    "toBeEncrypted"
})
public class EncryptCMSRequestType {

    @XmlElement(name = "RecipientPublicKey", required = true)
    protected List<CMSRecipientPublicKeyType> recipientPublicKey;
    @XmlElement(name = "ToBeEncrypted", required = true)
    protected CMSToBeEncryptedType toBeEncrypted;
    @XmlAttribute(name = "ReturnBinaryResult")
    protected Boolean returnBinaryResult;

    /**
     * Gets the value of the recipientPublicKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recipientPublicKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecipientPublicKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CMSRecipientPublicKeyType }
     * 
     * 
     */
    public List<CMSRecipientPublicKeyType> getRecipientPublicKey() {
        if (recipientPublicKey == null) {
            recipientPublicKey = new ArrayList<CMSRecipientPublicKeyType>();
        }
        return this.recipientPublicKey;
    }

    /**
     * Gets the value of the toBeEncrypted property.
     * 
     * @return
     *     possible object is
     *     {@link CMSToBeEncryptedType }
     *     
     */
    public CMSToBeEncryptedType getToBeEncrypted() {
        return toBeEncrypted;
    }

    /**
     * Sets the value of the toBeEncrypted property.
     * 
     * @param value
     *     allowed object is
     *     {@link CMSToBeEncryptedType }
     *     
     */
    public void setToBeEncrypted(CMSToBeEncryptedType value) {
        this.toBeEncrypted = value;
    }

    /**
     * Gets the value of the returnBinaryResult property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isReturnBinaryResult() {
        if (returnBinaryResult == null) {
            return false;
        } else {
            return returnBinaryResult;
        }
    }

    /**
     * Sets the value of the returnBinaryResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReturnBinaryResult(Boolean value) {
        this.returnBinaryResult = value;
    }

}
