//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 04:01:10 PM CEST 
//


package at.gv.egiz.sl.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for InfoboxCreateRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InfoboxCreateRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InfoboxIdentifier" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}BoxIdentifierType"/>
 *         &lt;element name="InfoboxType" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}InfoboxTypeType"/>
 *         &lt;element name="Creator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Purpose" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReadAccessAuthorization" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}AccessAuthorizationType" minOccurs="0"/>
 *         &lt;element name="UpdateAccessAuthorization" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}AccessAuthorizationType" minOccurs="0"/>
 *         &lt;element name="ReadUserConfirmation" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}UserConfirmationType" minOccurs="0"/>
 *         &lt;element name="UpdateUserConfirmation" type="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}UserConfirmationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfoboxCreateRequestType", propOrder = {
    "infoboxIdentifier",
    "infoboxType",
    "creator",
    "purpose",
    "readAccessAuthorization",
    "updateAccessAuthorization",
    "readUserConfirmation",
    "updateUserConfirmation"
})
public class InfoboxCreateRequestType {

    @XmlElement(name = "InfoboxIdentifier", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String infoboxIdentifier;
    @XmlElement(name = "InfoboxType", required = true)
    protected InfoboxTypeType infoboxType;
    @XmlElement(name = "Creator", required = true)
    protected String creator;
    @XmlElement(name = "Purpose", required = true)
    protected String purpose;
    @XmlElement(name = "ReadAccessAuthorization")
    protected AccessAuthorizationType readAccessAuthorization;
    @XmlElement(name = "UpdateAccessAuthorization")
    protected AccessAuthorizationType updateAccessAuthorization;
    @XmlElement(name = "ReadUserConfirmation")
    protected UserConfirmationType readUserConfirmation;
    @XmlElement(name = "UpdateUserConfirmation")
    protected UserConfirmationType updateUserConfirmation;

    /**
     * Gets the value of the infoboxIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfoboxIdentifier() {
        return infoboxIdentifier;
    }

    /**
     * Sets the value of the infoboxIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfoboxIdentifier(String value) {
        this.infoboxIdentifier = value;
    }

    /**
     * Gets the value of the infoboxType property.
     * 
     * @return
     *     possible object is
     *     {@link InfoboxTypeType }
     *     
     */
    public InfoboxTypeType getInfoboxType() {
        return infoboxType;
    }

    /**
     * Sets the value of the infoboxType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfoboxTypeType }
     *     
     */
    public void setInfoboxType(InfoboxTypeType value) {
        this.infoboxType = value;
    }

    /**
     * Gets the value of the creator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreator(String value) {
        this.creator = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurpose(String value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the readAccessAuthorization property.
     * 
     * @return
     *     possible object is
     *     {@link AccessAuthorizationType }
     *     
     */
    public AccessAuthorizationType getReadAccessAuthorization() {
        return readAccessAuthorization;
    }

    /**
     * Sets the value of the readAccessAuthorization property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessAuthorizationType }
     *     
     */
    public void setReadAccessAuthorization(AccessAuthorizationType value) {
        this.readAccessAuthorization = value;
    }

    /**
     * Gets the value of the updateAccessAuthorization property.
     * 
     * @return
     *     possible object is
     *     {@link AccessAuthorizationType }
     *     
     */
    public AccessAuthorizationType getUpdateAccessAuthorization() {
        return updateAccessAuthorization;
    }

    /**
     * Sets the value of the updateAccessAuthorization property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessAuthorizationType }
     *     
     */
    public void setUpdateAccessAuthorization(AccessAuthorizationType value) {
        this.updateAccessAuthorization = value;
    }

    /**
     * Gets the value of the readUserConfirmation property.
     * 
     * @return
     *     possible object is
     *     {@link UserConfirmationType }
     *     
     */
    public UserConfirmationType getReadUserConfirmation() {
        return readUserConfirmation;
    }

    /**
     * Sets the value of the readUserConfirmation property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserConfirmationType }
     *     
     */
    public void setReadUserConfirmation(UserConfirmationType value) {
        this.readUserConfirmation = value;
    }

    /**
     * Gets the value of the updateUserConfirmation property.
     * 
     * @return
     *     possible object is
     *     {@link UserConfirmationType }
     *     
     */
    public UserConfirmationType getUpdateUserConfirmation() {
        return updateUserConfirmation;
    }

    /**
     * Sets the value of the updateUserConfirmation property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserConfirmationType }
     *     
     */
    public void setUpdateUserConfirmation(UserConfirmationType value) {
        this.updateUserConfirmation = value;
    }

}
