//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 04:01:10 PM CEST 
//


package at.gv.egiz.sl.schema;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the at.gv.egiz.sl.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TransformTypeXPath_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "XPath");
    private final static QName _PGPData_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "PGPData");
    private final static QName _DecryptXMLResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "DecryptXMLResponse");
    private final static QName _GetPropertiesResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "GetPropertiesResponse");
    private final static QName _IdentityLinkDomainIdentifier_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "IdentityLinkDomainIdentifier");
    private final static QName _InfoboxDeleteResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "InfoboxDeleteResponse");
    private final static QName _EncryptCMSResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "EncryptCMSResponse");
    private final static QName _VerifyXMLSignatureResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "VerifyXMLSignatureResponse");
    private final static QName _SPKIData_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SPKIData");
    private final static QName _RetrievalMethod_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "RetrievalMethod");
    private final static QName _CanonicalizationMethod_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "CanonicalizationMethod");
    private final static QName _InfoboxUpdateRequest_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "InfoboxUpdateRequest");
    private final static QName _DecryptXMLRequest_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "DecryptXMLRequest");
    private final static QName _ErrorResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "ErrorResponse");
    private final static QName _SignatureProperty_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureProperty");
    private final static QName _CreateXMLSignatureRequest_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "CreateXMLSignatureRequest");
    private final static QName _Transforms_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Transforms");
    private final static QName _Manifest_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Manifest");
    private final static QName _InfoboxCreateResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "InfoboxCreateResponse");
    private final static QName _VerifyHashRequest_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "VerifyHashRequest");
    private final static QName _GetStatusRequest_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "GetStatusRequest");
    private final static QName _SignatureMethod_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureMethod");
    private final static QName _KeyInfo_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "KeyInfo");
    private final static QName _DigestMethod_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "DigestMethod");
    private final static QName _MgmtData_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "MgmtData");
    private final static QName _Reference_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Reference");
    private final static QName _VerifyXMLSignatureRequest_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "VerifyXMLSignatureRequest");
    private final static QName _InfoboxAvailableRequest_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "InfoboxAvailableRequest");
    private final static QName _VerifyHashResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "VerifyHashResponse");
    private final static QName _RSAKeyValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "RSAKeyValue");
    private final static QName _InfoboxUpdateResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "InfoboxUpdateResponse");
    private final static QName _Signature_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Signature");
    private final static QName _DSAKeyValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "DSAKeyValue");
    private final static QName _InfoboxDeleteRequest_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "InfoboxDeleteRequest");
    private final static QName _QualifiedCertificate_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "QualifiedCertificate");
    private final static QName _DecryptCMSRequest_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "DecryptCMSRequest");
    private final static QName _SignedInfo_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignedInfo");
    private final static QName _NullOperationResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "NullOperationResponse");
    private final static QName _InfoboxCreateRequest_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "InfoboxCreateRequest");
    private final static QName _Object_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Object");
    private final static QName _CreateHashResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "CreateHashResponse");
    private final static QName _SignatureValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureValue");
    private final static QName _Transform_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Transform");
    private final static QName _X509Data_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509Data");
    private final static QName _InfoboxReadRequest_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "InfoboxReadRequest");
    private final static QName _DecryptCMSResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "DecryptCMSResponse");
    private final static QName _EncryptCMSRequest_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "EncryptCMSRequest");
    private final static QName _EncryptXMLResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "EncryptXMLResponse");
    private final static QName _CreateHashRequest_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "CreateHashRequest");
    private final static QName _VerifyCMSSignatureRequest_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "VerifyCMSSignatureRequest");
    private final static QName _InfoboxReadResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "InfoboxReadResponse");
    private final static QName _DigestValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "DigestValue");
    private final static QName _NullOperationRequest_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "NullOperationRequest");
    private final static QName _SignatureProperties_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureProperties");
    private final static QName _KeyName_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "KeyName");
    private final static QName _GetStatusResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "GetStatusResponse");
    private final static QName _CreateCMSSignatureRequest_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "CreateCMSSignatureRequest");
    private final static QName _KeyValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "KeyValue");
    private final static QName _VerifyCMSSignatureResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "VerifyCMSSignatureResponse");
    private final static QName _CreateCMSSignatureResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "CreateCMSSignatureResponse");
    private final static QName _InfoboxAvailableResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "InfoboxAvailableResponse");
    private final static QName _CreateXMLSignatureResponse_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "CreateXMLSignatureResponse");
    private final static QName _X509DataTypeX509IssuerSerial_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509IssuerSerial");
    private final static QName _X509DataTypeX509Certificate_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509Certificate");
    private final static QName _X509DataTypeX509SKI_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509SKI");
    private final static QName _X509DataTypeX509SubjectName_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509SubjectName");
    private final static QName _X509DataTypeX509CRL_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509CRL");
    private final static QName _SignatureMethodTypeHMACOutputLength_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "HMACOutputLength");
    private final static QName _SPKIDataTypeSPKISexp_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SPKISexp");
    private final static QName _PGPDataTypePGPKeyID_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "PGPKeyID");
    private final static QName _PGPDataTypePGPKeyPacket_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "PGPKeyPacket");
    private final static QName _ReferencesCheckResultInfoTypeFailedReference_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "FailedReference");
    private final static QName _VerifyCMSSignatureResponseTypeSignatureCheck_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "SignatureCheck");
    private final static QName _VerifyCMSSignatureResponseTypeCertificateCheck_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "CertificateCheck");
    private final static QName _VerifyCMSSignatureResponseTypeSignerInfo_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "SignerInfo");
    private final static QName _ManifestRefsCheckResultInfoTypeReferringSigReference_QNAME = new QName("http://www.buergerkarte.at/namespaces/securitylayer/1.2#", "ReferringSigReference");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: at.gv.egiz.sl.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SignatureInfoCreationType }
     * 
     */
    public SignatureInfoCreationType createSignatureInfoCreationType() {
        return new SignatureInfoCreationType();
    }

    /**
     * Create an instance of {@link InfoboxReadParamsAssocArrayType }
     * 
     */
    public InfoboxReadParamsAssocArrayType createInfoboxReadParamsAssocArrayType() {
        return new InfoboxReadParamsAssocArrayType();
    }

    /**
     * Create an instance of {@link InfoboxUpdateParamsAssocArrayType }
     * 
     */
    public InfoboxUpdateParamsAssocArrayType createInfoboxUpdateParamsAssocArrayType() {
        return new InfoboxUpdateParamsAssocArrayType();
    }

    /**
     * Create an instance of {@link EncryptionInfoType }
     * 
     */
    public EncryptionInfoType createEncryptionInfoType() {
        return new EncryptionInfoType();
    }

    /**
     * Create an instance of {@link ToBeEncryptedType }
     * 
     */
    public ToBeEncryptedType createToBeEncryptedType() {
        return new ToBeEncryptedType();
    }

    /**
     * Create an instance of {@link EncryptXMLResponseType }
     * 
     */
    public EncryptXMLResponseType createEncryptXMLResponseType() {
        return new EncryptXMLResponseType();
    }

    /**
     * Create an instance of {@link DecryptXMLResponseType }
     * 
     */
    public DecryptXMLResponseType createDecryptXMLResponseType() {
        return new DecryptXMLResponseType();
    }

    /**
     * Create an instance of {@link EncryptCMSResponseType }
     * 
     */
    public EncryptCMSResponseType createEncryptCMSResponseType() {
        return new EncryptCMSResponseType();
    }

    /**
     * Create an instance of {@link VerifyXMLSignatureResponseType }
     * 
     */
    public VerifyXMLSignatureResponseType createVerifyXMLSignatureResponseType() {
        return new VerifyXMLSignatureResponseType();
    }

    /**
     * Create an instance of {@link CardChannelRequest }
     * 
     */
    public CardChannelRequest createCardChannelRequest() {
        return new CardChannelRequest();
    }

    /**
     * Create an instance of {@link ScriptElement }
     * 
     */
    public ScriptElement createScriptElement() {
        return new ScriptElement();
    }

    /**
     * Create an instance of {@link InfoboxDeleteResponseType }
     * 
     */
    public InfoboxDeleteResponseType createInfoboxDeleteResponseType() {
        return new InfoboxDeleteResponseType();
    }

    /**
     * Create an instance of {@link GetPropertiesRequest }
     * 
     */
    public GetPropertiesRequest createGetPropertiesRequest() {
        return new GetPropertiesRequest();
    }

    /**
     * Create an instance of {@link GetPropertiesRequestType }
     * 
     */
    public GetPropertiesRequestType createGetPropertiesRequestType() {
        return new GetPropertiesRequestType();
    }

    /**
     * Create an instance of {@link NullOperationResponseType }
     * 
     */
    public NullOperationResponseType createNullOperationResponseType() {
        return new NullOperationResponseType();
    }

    /**
     * Create an instance of {@link DecryptCMSRequestType }
     * 
     */
    public DecryptCMSRequestType createDecryptCMSRequestType() {
        return new DecryptCMSRequestType();
    }

    /**
     * Create an instance of {@link GetPropertiesResponseType }
     * 
     */
    public GetPropertiesResponseType createGetPropertiesResponseType() {
        return new GetPropertiesResponseType();
    }

    /**
     * Create an instance of {@link InfoboxDeleteRequestType }
     * 
     */
    public InfoboxDeleteRequestType createInfoboxDeleteRequestType() {
        return new InfoboxDeleteRequestType();
    }

    /**
     * Create an instance of {@link CardManagementRequest }
     * 
     */
    public CardManagementRequest createCardManagementRequest() {
        return new CardManagementRequest();
    }

    /**
     * Create an instance of {@link CardActionElement }
     * 
     */
    public CardActionElement createCardActionElement() {
        return new CardActionElement();
    }

    /**
     * Create an instance of {@link CreateXMLSignatureRequestType }
     * 
     */
    public CreateXMLSignatureRequestType createCreateXMLSignatureRequestType() {
        return new CreateXMLSignatureRequestType();
    }

    /**
     * Create an instance of {@link InfoboxCreateResponseType }
     * 
     */
    public InfoboxCreateResponseType createInfoboxCreateResponseType() {
        return new InfoboxCreateResponseType();
    }

    /**
     * Create an instance of {@link CardChannelResponse }
     * 
     */
    public CardChannelResponse createCardChannelResponse() {
        return new CardChannelResponse();
    }

    /**
     * Create an instance of {@link APDUResponseElement }
     * 
     */
    public APDUResponseElement createAPDUResponseElement() {
        return new APDUResponseElement();
    }

    /**
     * Create an instance of {@link CardManagementResponse }
     * 
     */
    public CardManagementResponse createCardManagementResponse() {
        return new CardManagementResponse();
    }

    /**
     * Create an instance of {@link ResultElement }
     * 
     */
    public ResultElement createResultElement() {
        return new ResultElement();
    }

    /**
     * Create an instance of {@link InfoboxUpdateRequestType }
     * 
     */
    public InfoboxUpdateRequestType createInfoboxUpdateRequestType() {
        return new InfoboxUpdateRequestType();
    }

    /**
     * Create an instance of {@link InfoboxCreateRequestType }
     * 
     */
    public InfoboxCreateRequestType createInfoboxCreateRequestType() {
        return new InfoboxCreateRequestType();
    }

    /**
     * Create an instance of {@link ErrorResponseType }
     * 
     */
    public ErrorResponseType createErrorResponseType() {
        return new ErrorResponseType();
    }

    /**
     * Create an instance of {@link DecryptXMLRequestType }
     * 
     */
    public DecryptXMLRequestType createDecryptXMLRequestType() {
        return new DecryptXMLRequestType();
    }

    /**
     * Create an instance of {@link CreateHashResponseType }
     * 
     */
    public CreateHashResponseType createCreateHashResponseType() {
        return new CreateHashResponseType();
    }

    /**
     * Create an instance of {@link CreateHashRequestType }
     * 
     */
    public CreateHashRequestType createCreateHashRequestType() {
        return new CreateHashRequestType();
    }

    /**
     * Create an instance of {@link EncryptCMSRequestType }
     * 
     */
    public EncryptCMSRequestType createEncryptCMSRequestType() {
        return new EncryptCMSRequestType();
    }

    /**
     * Create an instance of {@link InfoboxReadResponseType }
     * 
     */
    public InfoboxReadResponseType createInfoboxReadResponseType() {
        return new InfoboxReadResponseType();
    }

    /**
     * Create an instance of {@link VerifyCMSSignatureRequestType }
     * 
     */
    public VerifyCMSSignatureRequestType createVerifyCMSSignatureRequestType() {
        return new VerifyCMSSignatureRequestType();
    }

    /**
     * Create an instance of {@link InfoboxReadRequestType }
     * 
     */
    public InfoboxReadRequestType createInfoboxReadRequestType() {
        return new InfoboxReadRequestType();
    }

    /**
     * Create an instance of {@link VerifyHashRequestType }
     * 
     */
    public VerifyHashRequestType createVerifyHashRequestType() {
        return new VerifyHashRequestType();
    }

    /**
     * Create an instance of {@link GetStatusRequestType }
     * 
     */
    public GetStatusRequestType createGetStatusRequestType() {
        return new GetStatusRequestType();
    }

    /**
     * Create an instance of {@link DecryptCMSResponseType }
     * 
     */
    public DecryptCMSResponseType createDecryptCMSResponseType() {
        return new DecryptCMSResponseType();
    }

    /**
     * Create an instance of {@link VerifyHashResponseType }
     * 
     */
    public VerifyHashResponseType createVerifyHashResponseType() {
        return new VerifyHashResponseType();
    }

    /**
     * Create an instance of {@link InfoboxAvailableResponseType }
     * 
     */
    public InfoboxAvailableResponseType createInfoboxAvailableResponseType() {
        return new InfoboxAvailableResponseType();
    }

    /**
     * Create an instance of {@link InfoboxAvailableRequestType }
     * 
     */
    public InfoboxAvailableRequestType createInfoboxAvailableRequestType() {
        return new InfoboxAvailableRequestType();
    }

    /**
     * Create an instance of {@link InfoboxUpdateResponseType }
     * 
     */
    public InfoboxUpdateResponseType createInfoboxUpdateResponseType() {
        return new InfoboxUpdateResponseType();
    }

    /**
     * Create an instance of {@link CreateXMLSignatureResponseType }
     * 
     */
    public CreateXMLSignatureResponseType createCreateXMLSignatureResponseType() {
        return new CreateXMLSignatureResponseType();
    }

    /**
     * Create an instance of {@link GetStatusResponseType }
     * 
     */
    public GetStatusResponseType createGetStatusResponseType() {
        return new GetStatusResponseType();
    }

    /**
     * Create an instance of {@link CreateCMSSignatureRequestType }
     * 
     */
    public CreateCMSSignatureRequestType createCreateCMSSignatureRequestType() {
        return new CreateCMSSignatureRequestType();
    }

    /**
     * Create an instance of {@link NullOperationRequestType }
     * 
     */
    public NullOperationRequestType createNullOperationRequestType() {
        return new NullOperationRequestType();
    }

    /**
     * Create an instance of {@link VerifyXMLSignatureRequestType }
     * 
     */
    public VerifyXMLSignatureRequestType createVerifyXMLSignatureRequestType() {
        return new VerifyXMLSignatureRequestType();
    }

    /**
     * Create an instance of {@link CreateCMSSignatureResponseType }
     * 
     */
    public CreateCMSSignatureResponseType createCreateCMSSignatureResponseType() {
        return new CreateCMSSignatureResponseType();
    }

    /**
     * Create an instance of {@link EncryptXMLRequest }
     * 
     */
    public EncryptXMLRequest createEncryptXMLRequest() {
        return new EncryptXMLRequest();
    }

    /**
     * Create an instance of {@link EncryptXMLRequestType }
     * 
     */
    public EncryptXMLRequestType createEncryptXMLRequestType() {
        return new EncryptXMLRequestType();
    }

    /**
     * Create an instance of {@link XMLRecipientPublicKeyType }
     * 
     */
    public XMLRecipientPublicKeyType createXMLRecipientPublicKeyType() {
        return new XMLRecipientPublicKeyType();
    }

    /**
     * Create an instance of {@link VerifyCMSSignatureResponseType }
     * 
     */
    public VerifyCMSSignatureResponseType createVerifyCMSSignatureResponseType() {
        return new VerifyCMSSignatureResponseType();
    }

    /**
     * Create an instance of {@link CMSRecipientPublicKeyType }
     * 
     */
    public CMSRecipientPublicKeyType createCMSRecipientPublicKeyType() {
        return new CMSRecipientPublicKeyType();
    }

    /**
     * Create an instance of {@link InfoboxReadParamsBinaryFileType }
     * 
     */
    public InfoboxReadParamsBinaryFileType createInfoboxReadParamsBinaryFileType() {
        return new InfoboxReadParamsBinaryFileType();
    }

    /**
     * Create an instance of {@link CMSEncryptedContentType }
     * 
     */
    public CMSEncryptedContentType createCMSEncryptedContentType() {
        return new CMSEncryptedContentType();
    }

    /**
     * Create an instance of {@link SignatureInfoVerificationType }
     * 
     */
    public SignatureInfoVerificationType createSignatureInfoVerificationType() {
        return new SignatureInfoVerificationType();
    }

    /**
     * Create an instance of {@link CreateHashInfoResponseType }
     * 
     */
    public CreateHashInfoResponseType createCreateHashInfoResponseType() {
        return new CreateHashInfoResponseType();
    }

    /**
     * Create an instance of {@link BindingType }
     * 
     */
    public BindingType createBindingType() {
        return new BindingType();
    }

    /**
     * Create an instance of {@link Base64XMLLocRefOptRefContentType }
     * 
     */
    public Base64XMLLocRefOptRefContentType createBase64XMLLocRefOptRefContentType() {
        return new Base64XMLLocRefOptRefContentType();
    }

    /**
     * Create an instance of {@link CMSDataObjectOptionalMetaType }
     * 
     */
    public CMSDataObjectOptionalMetaType createCMSDataObjectOptionalMetaType() {
        return new CMSDataObjectOptionalMetaType();
    }

    /**
     * Create an instance of {@link ResponseAPDUType }
     * 
     */
    public ResponseAPDUType createResponseAPDUType() {
        return new ResponseAPDUType();
    }

    /**
     * Create an instance of {@link Base64ContentType }
     * 
     */
    public Base64ContentType createBase64ContentType() {
        return new Base64ContentType();
    }

    /**
     * Create an instance of {@link InfoboxAssocArrayPairType }
     * 
     */
    public InfoboxAssocArrayPairType createInfoboxAssocArrayPairType() {
        return new InfoboxAssocArrayPairType();
    }

    /**
     * Create an instance of {@link CMSToBeEncryptedType }
     * 
     */
    public CMSToBeEncryptedType createCMSToBeEncryptedType() {
        return new CMSToBeEncryptedType();
    }

    /**
     * Create an instance of {@link Base64XMLOptRefContentType }
     * 
     */
    public Base64XMLOptRefContentType createBase64XMLOptRefContentType() {
        return new Base64XMLOptRefContentType();
    }

    /**
     * Create an instance of {@link ReferencesCheckResultInfoType }
     * 
     */
    public ReferencesCheckResultInfoType createReferencesCheckResultInfoType() {
        return new ReferencesCheckResultInfoType();
    }

    /**
     * Create an instance of {@link Base64XMLContentType }
     * 
     */
    public Base64XMLContentType createBase64XMLContentType() {
        return new Base64XMLContentType();
    }

    /**
     * Create an instance of {@link HashDataType }
     * 
     */
    public HashDataType createHashDataType() {
        return new HashDataType();
    }

    /**
     * Create an instance of {@link CMSDataObjectRequiredMetaType }
     * 
     */
    public CMSDataObjectRequiredMetaType createCMSDataObjectRequiredMetaType() {
        return new CMSDataObjectRequiredMetaType();
    }

    /**
     * Create an instance of {@link XMLContentType }
     * 
     */
    public XMLContentType createXMLContentType() {
        return new XMLContentType();
    }

    /**
     * Create an instance of {@link AnyMixedChildrenType }
     * 
     */
    public AnyMixedChildrenType createAnyMixedChildrenType() {
        return new AnyMixedChildrenType();
    }

    /**
     * Create an instance of {@link AnyChildrenType }
     * 
     */
    public AnyChildrenType createAnyChildrenType() {
        return new AnyChildrenType();
    }

    /**
     * Create an instance of {@link ManifestRefsCheckResultInfoType }
     * 
     */
    public ManifestRefsCheckResultInfoType createManifestRefsCheckResultInfoType() {
        return new ManifestRefsCheckResultInfoType();
    }

    /**
     * Create an instance of {@link Base64XMLLocRefReqRefContentType }
     * 
     */
    public Base64XMLLocRefReqRefContentType createBase64XMLLocRefReqRefContentType() {
        return new Base64XMLLocRefReqRefContentType();
    }

    /**
     * Create an instance of {@link UserConfirmationType }
     * 
     */
    public UserConfirmationType createUserConfirmationType() {
        return new UserConfirmationType();
    }

    /**
     * Create an instance of {@link DataObjectInfoType }
     * 
     */
    public DataObjectInfoType createDataObjectInfoType() {
        return new DataObjectInfoType();
    }

    /**
     * Create an instance of {@link APDUATRType }
     * 
     */
    public APDUATRType createAPDUATRType() {
        return new APDUATRType();
    }

    /**
     * Create an instance of {@link ResultApplElement }
     * 
     */
    public ResultApplElement createResultApplElement() {
        return new ResultApplElement();
    }

    /**
     * Create an instance of {@link VerificationResultType }
     * 
     */
    public VerificationResultType createVerificationResultType() {
        return new VerificationResultType();
    }

    /**
     * Create an instance of {@link ExcludedByteRangeType }
     * 
     */
    public ExcludedByteRangeType createExcludedByteRangeType() {
        return new ExcludedByteRangeType();
    }

    /**
     * Create an instance of {@link ManifestRefsCheckResultType }
     * 
     */
    public ManifestRefsCheckResultType createManifestRefsCheckResultType() {
        return new ManifestRefsCheckResultType();
    }

    /**
     * Create an instance of {@link CheckResultType }
     * 
     */
    public CheckResultType createCheckResultType() {
        return new CheckResultType();
    }

    /**
     * Create an instance of {@link EncryptedDataType }
     * 
     */
    public EncryptedDataType createEncryptedDataType() {
        return new EncryptedDataType();
    }

    /**
     * Create an instance of {@link InfoboxReadDataAssocArrayType }
     * 
     */
    public InfoboxReadDataAssocArrayType createInfoboxReadDataAssocArrayType() {
        return new InfoboxReadDataAssocArrayType();
    }

    /**
     * Create an instance of {@link TransformsInfoType }
     * 
     */
    public TransformsInfoType createTransformsInfoType() {
        return new TransformsInfoType();
    }

    /**
     * Create an instance of {@link QualifiedBoxIdentifierType }
     * 
     */
    public QualifiedBoxIdentifierType createQualifiedBoxIdentifierType() {
        return new QualifiedBoxIdentifierType();
    }

    /**
     * Create an instance of {@link VerifyHashInfoRequestType }
     * 
     */
    public VerifyHashInfoRequestType createVerifyHashInfoRequestType() {
        return new VerifyHashInfoRequestType();
    }

    /**
     * Create an instance of {@link XMLToBeEncryptedNewContentType }
     * 
     */
    public XMLToBeEncryptedNewContentType createXMLToBeEncryptedNewContentType() {
        return new XMLToBeEncryptedNewContentType();
    }

    /**
     * Create an instance of {@link Base64XMLLocRefContentType }
     * 
     */
    public Base64XMLLocRefContentType createBase64XMLLocRefContentType() {
        return new Base64XMLLocRefContentType();
    }

    /**
     * Create an instance of {@link Base64OptRefContentType }
     * 
     */
    public Base64OptRefContentType createBase64OptRefContentType() {
        return new Base64OptRefContentType();
    }

    /**
     * Create an instance of {@link CreateHashInfoRequestType }
     * 
     */
    public CreateHashInfoRequestType createCreateHashInfoRequestType() {
        return new CreateHashInfoRequestType();
    }

    /**
     * Create an instance of {@link XMLToBeEncryptedNewType }
     * 
     */
    public XMLToBeEncryptedNewType createXMLToBeEncryptedNewType() {
        return new XMLToBeEncryptedNewType();
    }

    /**
     * Create an instance of {@link ResetType }
     * 
     */
    public ResetType createResetType() {
        return new ResetType();
    }

    /**
     * Create an instance of {@link AccessAuthorizationType }
     * 
     */
    public AccessAuthorizationType createAccessAuthorizationType() {
        return new AccessAuthorizationType();
    }

    /**
     * Create an instance of {@link MetaInfoType }
     * 
     */
    public MetaInfoType createMetaInfoType() {
        return new MetaInfoType();
    }

    /**
     * Create an instance of {@link DataObjectAssociationType }
     * 
     */
    public DataObjectAssociationType createDataObjectAssociationType() {
        return new DataObjectAssociationType();
    }

    /**
     * Create an instance of {@link ReferencesCheckResultType }
     * 
     */
    public ReferencesCheckResultType createReferencesCheckResultType() {
        return new ReferencesCheckResultType();
    }

    /**
     * Create an instance of {@link RequesterIDType }
     * 
     */
    public RequesterIDType createRequesterIDType() {
        return new RequesterIDType();
    }

    /**
     * Create an instance of {@link CommandAPDUType }
     * 
     */
    public CommandAPDUType createCommandAPDUType() {
        return new CommandAPDUType();
    }

    /**
     * Create an instance of {@link KeyInfoType }
     * 
     */
    public KeyInfoType createKeyInfoType() {
        return new KeyInfoType();
    }

    /**
     * Create an instance of {@link SignedInfoType }
     * 
     */
    public SignedInfoType createSignedInfoType() {
        return new SignedInfoType();
    }

    /**
     * Create an instance of {@link RetrievalMethodType }
     * 
     */
    public RetrievalMethodType createRetrievalMethodType() {
        return new RetrievalMethodType();
    }

    /**
     * Create an instance of {@link DigestMethodType }
     * 
     */
    public DigestMethodType createDigestMethodType() {
        return new DigestMethodType();
    }

    /**
     * Create an instance of {@link SignatureMethodType }
     * 
     */
    public SignatureMethodType createSignatureMethodType() {
        return new SignatureMethodType();
    }

    /**
     * Create an instance of {@link SPKIDataType }
     * 
     */
    public SPKIDataType createSPKIDataType() {
        return new SPKIDataType();
    }

    /**
     * Create an instance of {@link X509DataType }
     * 
     */
    public X509DataType createX509DataType() {
        return new X509DataType();
    }

    /**
     * Create an instance of {@link PGPDataType }
     * 
     */
    public PGPDataType createPGPDataType() {
        return new PGPDataType();
    }

    /**
     * Create an instance of {@link SignatureType }
     * 
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link DSAKeyValueType }
     * 
     */
    public DSAKeyValueType createDSAKeyValueType() {
        return new DSAKeyValueType();
    }

    /**
     * Create an instance of {@link ManifestType }
     * 
     */
    public ManifestType createManifestType() {
        return new ManifestType();
    }

    /**
     * Create an instance of {@link SignatureValueType }
     * 
     */
    public SignatureValueType createSignatureValueType() {
        return new SignatureValueType();
    }

    /**
     * Create an instance of {@link TransformsType }
     * 
     */
    public TransformsType createTransformsType() {
        return new TransformsType();
    }

    /**
     * Create an instance of {@link RSAKeyValueType }
     * 
     */
    public RSAKeyValueType createRSAKeyValueType() {
        return new RSAKeyValueType();
    }

    /**
     * Create an instance of {@link TransformType }
     * 
     */
    public TransformType createTransformType() {
        return new TransformType();
    }

    /**
     * Create an instance of {@link SignaturePropertyType }
     * 
     */
    public SignaturePropertyType createSignaturePropertyType() {
        return new SignaturePropertyType();
    }

    /**
     * Create an instance of {@link KeyValueType }
     * 
     */
    public KeyValueType createKeyValueType() {
        return new KeyValueType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link CanonicalizationMethodType }
     * 
     */
    public CanonicalizationMethodType createCanonicalizationMethodType() {
        return new CanonicalizationMethodType();
    }

    /**
     * Create an instance of {@link SignaturePropertiesType }
     * 
     */
    public SignaturePropertiesType createSignaturePropertiesType() {
        return new SignaturePropertiesType();
    }

    /**
     * Create an instance of {@link ObjectType }
     * 
     */
    public ObjectType createObjectType() {
        return new ObjectType();
    }

    /**
     * Create an instance of {@link X509IssuerSerialType }
     * 
     */
    public X509IssuerSerialType createX509IssuerSerialType() {
        return new X509IssuerSerialType();
    }

    /**
     * Create an instance of {@link SignatureInfoCreationType.SignatureLocation }
     * 
     */
    public SignatureInfoCreationType.SignatureLocation createSignatureInfoCreationTypeSignatureLocation() {
        return new SignatureInfoCreationType.SignatureLocation();
    }

    /**
     * Create an instance of {@link InfoboxReadParamsAssocArrayType.ReadKeys }
     * 
     */
    public InfoboxReadParamsAssocArrayType.ReadKeys createInfoboxReadParamsAssocArrayTypeReadKeys() {
        return new InfoboxReadParamsAssocArrayType.ReadKeys();
    }

    /**
     * Create an instance of {@link InfoboxReadParamsAssocArrayType.ReadPairs }
     * 
     */
    public InfoboxReadParamsAssocArrayType.ReadPairs createInfoboxReadParamsAssocArrayTypeReadPairs() {
        return new InfoboxReadParamsAssocArrayType.ReadPairs();
    }

    /**
     * Create an instance of {@link InfoboxReadParamsAssocArrayType.ReadValue }
     * 
     */
    public InfoboxReadParamsAssocArrayType.ReadValue createInfoboxReadParamsAssocArrayTypeReadValue() {
        return new InfoboxReadParamsAssocArrayType.ReadValue();
    }

    /**
     * Create an instance of {@link InfoboxUpdateParamsAssocArrayType.UpdateKey }
     * 
     */
    public InfoboxUpdateParamsAssocArrayType.UpdateKey createInfoboxUpdateParamsAssocArrayTypeUpdateKey() {
        return new InfoboxUpdateParamsAssocArrayType.UpdateKey();
    }

    /**
     * Create an instance of {@link InfoboxUpdateParamsAssocArrayType.DeletePair }
     * 
     */
    public InfoboxUpdateParamsAssocArrayType.DeletePair createInfoboxUpdateParamsAssocArrayTypeDeletePair() {
        return new InfoboxUpdateParamsAssocArrayType.DeletePair();
    }

    /**
     * Create an instance of {@link EncryptionInfoType.EncryptedKeyLocation }
     * 
     */
    public EncryptionInfoType.EncryptedKeyLocation createEncryptionInfoTypeEncryptedKeyLocation() {
        return new EncryptionInfoType.EncryptedKeyLocation();
    }

    /**
     * Create an instance of {@link ToBeEncryptedType.Element }
     * 
     */
    public ToBeEncryptedType.Element createToBeEncryptedTypeElement() {
        return new ToBeEncryptedType.Element();
    }

    /**
     * Create an instance of {@link ToBeEncryptedType.ElementContent }
     * 
     */
    public ToBeEncryptedType.ElementContent createToBeEncryptedTypeElementContent() {
        return new ToBeEncryptedType.ElementContent();
    }

    /**
     * Create an instance of {@link EncryptXMLResponseType.EncryptionEnvironment }
     * 
     */
    public EncryptXMLResponseType.EncryptionEnvironment createEncryptXMLResponseTypeEncryptionEnvironment() {
        return new EncryptXMLResponseType.EncryptionEnvironment();
    }

    /**
     * Create an instance of {@link DecryptXMLResponseType.DecryptedBinaryData }
     * 
     */
    public DecryptXMLResponseType.DecryptedBinaryData createDecryptXMLResponseTypeDecryptedBinaryData() {
        return new DecryptXMLResponseType.DecryptedBinaryData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "XPath", scope = TransformType.class)
    public JAXBElement<String> createTransformTypeXPath(String value) {
        return new JAXBElement<String>(_TransformTypeXPath_QNAME, String.class, TransformType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PGPDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "PGPData")
    public JAXBElement<PGPDataType> createPGPData(PGPDataType value) {
        return new JAXBElement<PGPDataType>(_PGPData_QNAME, PGPDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DecryptXMLResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "DecryptXMLResponse")
    public JAXBElement<DecryptXMLResponseType> createDecryptXMLResponse(DecryptXMLResponseType value) {
        return new JAXBElement<DecryptXMLResponseType>(_DecryptXMLResponse_QNAME, DecryptXMLResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPropertiesResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "GetPropertiesResponse")
    public JAXBElement<GetPropertiesResponseType> createGetPropertiesResponse(GetPropertiesResponseType value) {
        return new JAXBElement<GetPropertiesResponseType>(_GetPropertiesResponse_QNAME, GetPropertiesResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "IdentityLinkDomainIdentifier")
    public JAXBElement<String> createIdentityLinkDomainIdentifier(String value) {
        return new JAXBElement<String>(_IdentityLinkDomainIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoboxDeleteResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "InfoboxDeleteResponse")
    public JAXBElement<InfoboxDeleteResponseType> createInfoboxDeleteResponse(InfoboxDeleteResponseType value) {
        return new JAXBElement<InfoboxDeleteResponseType>(_InfoboxDeleteResponse_QNAME, InfoboxDeleteResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncryptCMSResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "EncryptCMSResponse")
    public JAXBElement<EncryptCMSResponseType> createEncryptCMSResponse(EncryptCMSResponseType value) {
        return new JAXBElement<EncryptCMSResponseType>(_EncryptCMSResponse_QNAME, EncryptCMSResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VerifyXMLSignatureResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "VerifyXMLSignatureResponse")
    public JAXBElement<VerifyXMLSignatureResponseType> createVerifyXMLSignatureResponse(VerifyXMLSignatureResponseType value) {
        return new JAXBElement<VerifyXMLSignatureResponseType>(_VerifyXMLSignatureResponse_QNAME, VerifyXMLSignatureResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SPKIDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SPKIData")
    public JAXBElement<SPKIDataType> createSPKIData(SPKIDataType value) {
        return new JAXBElement<SPKIDataType>(_SPKIData_QNAME, SPKIDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetrievalMethodType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "RetrievalMethod")
    public JAXBElement<RetrievalMethodType> createRetrievalMethod(RetrievalMethodType value) {
        return new JAXBElement<RetrievalMethodType>(_RetrievalMethod_QNAME, RetrievalMethodType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CanonicalizationMethodType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "CanonicalizationMethod")
    public JAXBElement<CanonicalizationMethodType> createCanonicalizationMethod(CanonicalizationMethodType value) {
        return new JAXBElement<CanonicalizationMethodType>(_CanonicalizationMethod_QNAME, CanonicalizationMethodType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoboxUpdateRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "InfoboxUpdateRequest")
    public JAXBElement<InfoboxUpdateRequestType> createInfoboxUpdateRequest(InfoboxUpdateRequestType value) {
        return new JAXBElement<InfoboxUpdateRequestType>(_InfoboxUpdateRequest_QNAME, InfoboxUpdateRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DecryptXMLRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "DecryptXMLRequest")
    public JAXBElement<DecryptXMLRequestType> createDecryptXMLRequest(DecryptXMLRequestType value) {
        return new JAXBElement<DecryptXMLRequestType>(_DecryptXMLRequest_QNAME, DecryptXMLRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErrorResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "ErrorResponse")
    public JAXBElement<ErrorResponseType> createErrorResponse(ErrorResponseType value) {
        return new JAXBElement<ErrorResponseType>(_ErrorResponse_QNAME, ErrorResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignaturePropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignatureProperty")
    public JAXBElement<SignaturePropertyType> createSignatureProperty(SignaturePropertyType value) {
        return new JAXBElement<SignaturePropertyType>(_SignatureProperty_QNAME, SignaturePropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateXMLSignatureRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "CreateXMLSignatureRequest")
    public JAXBElement<CreateXMLSignatureRequestType> createCreateXMLSignatureRequest(CreateXMLSignatureRequestType value) {
        return new JAXBElement<CreateXMLSignatureRequestType>(_CreateXMLSignatureRequest_QNAME, CreateXMLSignatureRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransformsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Transforms")
    public JAXBElement<TransformsType> createTransforms(TransformsType value) {
        return new JAXBElement<TransformsType>(_Transforms_QNAME, TransformsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ManifestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Manifest")
    public JAXBElement<ManifestType> createManifest(ManifestType value) {
        return new JAXBElement<ManifestType>(_Manifest_QNAME, ManifestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoboxCreateResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "InfoboxCreateResponse")
    public JAXBElement<InfoboxCreateResponseType> createInfoboxCreateResponse(InfoboxCreateResponseType value) {
        return new JAXBElement<InfoboxCreateResponseType>(_InfoboxCreateResponse_QNAME, InfoboxCreateResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VerifyHashRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "VerifyHashRequest")
    public JAXBElement<VerifyHashRequestType> createVerifyHashRequest(VerifyHashRequestType value) {
        return new JAXBElement<VerifyHashRequestType>(_VerifyHashRequest_QNAME, VerifyHashRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStatusRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "GetStatusRequest")
    public JAXBElement<GetStatusRequestType> createGetStatusRequest(GetStatusRequestType value) {
        return new JAXBElement<GetStatusRequestType>(_GetStatusRequest_QNAME, GetStatusRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureMethodType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignatureMethod")
    public JAXBElement<SignatureMethodType> createSignatureMethod(SignatureMethodType value) {
        return new JAXBElement<SignatureMethodType>(_SignatureMethod_QNAME, SignatureMethodType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeyInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "KeyInfo")
    public JAXBElement<KeyInfoType> createKeyInfo(KeyInfoType value) {
        return new JAXBElement<KeyInfoType>(_KeyInfo_QNAME, KeyInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DigestMethodType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "DigestMethod")
    public JAXBElement<DigestMethodType> createDigestMethod(DigestMethodType value) {
        return new JAXBElement<DigestMethodType>(_DigestMethod_QNAME, DigestMethodType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "MgmtData")
    public JAXBElement<String> createMgmtData(String value) {
        return new JAXBElement<String>(_MgmtData_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Reference")
    public JAXBElement<ReferenceType> createReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_Reference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VerifyXMLSignatureRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "VerifyXMLSignatureRequest")
    public JAXBElement<VerifyXMLSignatureRequestType> createVerifyXMLSignatureRequest(VerifyXMLSignatureRequestType value) {
        return new JAXBElement<VerifyXMLSignatureRequestType>(_VerifyXMLSignatureRequest_QNAME, VerifyXMLSignatureRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoboxAvailableRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "InfoboxAvailableRequest")
    public JAXBElement<InfoboxAvailableRequestType> createInfoboxAvailableRequest(InfoboxAvailableRequestType value) {
        return new JAXBElement<InfoboxAvailableRequestType>(_InfoboxAvailableRequest_QNAME, InfoboxAvailableRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VerifyHashResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "VerifyHashResponse")
    public JAXBElement<VerifyHashResponseType> createVerifyHashResponse(VerifyHashResponseType value) {
        return new JAXBElement<VerifyHashResponseType>(_VerifyHashResponse_QNAME, VerifyHashResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RSAKeyValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "RSAKeyValue")
    public JAXBElement<RSAKeyValueType> createRSAKeyValue(RSAKeyValueType value) {
        return new JAXBElement<RSAKeyValueType>(_RSAKeyValue_QNAME, RSAKeyValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoboxUpdateResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "InfoboxUpdateResponse")
    public JAXBElement<InfoboxUpdateResponseType> createInfoboxUpdateResponse(InfoboxUpdateResponseType value) {
        return new JAXBElement<InfoboxUpdateResponseType>(_InfoboxUpdateResponse_QNAME, InfoboxUpdateResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Signature")
    public JAXBElement<SignatureType> createSignature(SignatureType value) {
        return new JAXBElement<SignatureType>(_Signature_QNAME, SignatureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DSAKeyValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "DSAKeyValue")
    public JAXBElement<DSAKeyValueType> createDSAKeyValue(DSAKeyValueType value) {
        return new JAXBElement<DSAKeyValueType>(_DSAKeyValue_QNAME, DSAKeyValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoboxDeleteRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "InfoboxDeleteRequest")
    public JAXBElement<InfoboxDeleteRequestType> createInfoboxDeleteRequest(InfoboxDeleteRequestType value) {
        return new JAXBElement<InfoboxDeleteRequestType>(_InfoboxDeleteRequest_QNAME, InfoboxDeleteRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "QualifiedCertificate")
    public JAXBElement<Object> createQualifiedCertificate(Object value) {
        return new JAXBElement<Object>(_QualifiedCertificate_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DecryptCMSRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "DecryptCMSRequest")
    public JAXBElement<DecryptCMSRequestType> createDecryptCMSRequest(DecryptCMSRequestType value) {
        return new JAXBElement<DecryptCMSRequestType>(_DecryptCMSRequest_QNAME, DecryptCMSRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignedInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignedInfo")
    public JAXBElement<SignedInfoType> createSignedInfo(SignedInfoType value) {
        return new JAXBElement<SignedInfoType>(_SignedInfo_QNAME, SignedInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NullOperationResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "NullOperationResponse")
    public JAXBElement<NullOperationResponseType> createNullOperationResponse(NullOperationResponseType value) {
        return new JAXBElement<NullOperationResponseType>(_NullOperationResponse_QNAME, NullOperationResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoboxCreateRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "InfoboxCreateRequest")
    public JAXBElement<InfoboxCreateRequestType> createInfoboxCreateRequest(InfoboxCreateRequestType value) {
        return new JAXBElement<InfoboxCreateRequestType>(_InfoboxCreateRequest_QNAME, InfoboxCreateRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Object")
    public JAXBElement<ObjectType> createObject(ObjectType value) {
        return new JAXBElement<ObjectType>(_Object_QNAME, ObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateHashResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "CreateHashResponse")
    public JAXBElement<CreateHashResponseType> createCreateHashResponse(CreateHashResponseType value) {
        return new JAXBElement<CreateHashResponseType>(_CreateHashResponse_QNAME, CreateHashResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignatureValue")
    public JAXBElement<SignatureValueType> createSignatureValue(SignatureValueType value) {
        return new JAXBElement<SignatureValueType>(_SignatureValue_QNAME, SignatureValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransformType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Transform")
    public JAXBElement<TransformType> createTransform(TransformType value) {
        return new JAXBElement<TransformType>(_Transform_QNAME, TransformType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link X509DataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509Data")
    public JAXBElement<X509DataType> createX509Data(X509DataType value) {
        return new JAXBElement<X509DataType>(_X509Data_QNAME, X509DataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoboxReadRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "InfoboxReadRequest")
    public JAXBElement<InfoboxReadRequestType> createInfoboxReadRequest(InfoboxReadRequestType value) {
        return new JAXBElement<InfoboxReadRequestType>(_InfoboxReadRequest_QNAME, InfoboxReadRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DecryptCMSResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "DecryptCMSResponse")
    public JAXBElement<DecryptCMSResponseType> createDecryptCMSResponse(DecryptCMSResponseType value) {
        return new JAXBElement<DecryptCMSResponseType>(_DecryptCMSResponse_QNAME, DecryptCMSResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncryptCMSRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "EncryptCMSRequest")
    public JAXBElement<EncryptCMSRequestType> createEncryptCMSRequest(EncryptCMSRequestType value) {
        return new JAXBElement<EncryptCMSRequestType>(_EncryptCMSRequest_QNAME, EncryptCMSRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncryptXMLResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "EncryptXMLResponse")
    public JAXBElement<EncryptXMLResponseType> createEncryptXMLResponse(EncryptXMLResponseType value) {
        return new JAXBElement<EncryptXMLResponseType>(_EncryptXMLResponse_QNAME, EncryptXMLResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateHashRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "CreateHashRequest")
    public JAXBElement<CreateHashRequestType> createCreateHashRequest(CreateHashRequestType value) {
        return new JAXBElement<CreateHashRequestType>(_CreateHashRequest_QNAME, CreateHashRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VerifyCMSSignatureRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "VerifyCMSSignatureRequest")
    public JAXBElement<VerifyCMSSignatureRequestType> createVerifyCMSSignatureRequest(VerifyCMSSignatureRequestType value) {
        return new JAXBElement<VerifyCMSSignatureRequestType>(_VerifyCMSSignatureRequest_QNAME, VerifyCMSSignatureRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoboxReadResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "InfoboxReadResponse")
    public JAXBElement<InfoboxReadResponseType> createInfoboxReadResponse(InfoboxReadResponseType value) {
        return new JAXBElement<InfoboxReadResponseType>(_InfoboxReadResponse_QNAME, InfoboxReadResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "DigestValue")
    public JAXBElement<byte[]> createDigestValue(byte[] value) {
        return new JAXBElement<byte[]>(_DigestValue_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NullOperationRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "NullOperationRequest")
    public JAXBElement<NullOperationRequestType> createNullOperationRequest(NullOperationRequestType value) {
        return new JAXBElement<NullOperationRequestType>(_NullOperationRequest_QNAME, NullOperationRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignaturePropertiesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignatureProperties")
    public JAXBElement<SignaturePropertiesType> createSignatureProperties(SignaturePropertiesType value) {
        return new JAXBElement<SignaturePropertiesType>(_SignatureProperties_QNAME, SignaturePropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "KeyName")
    public JAXBElement<String> createKeyName(String value) {
        return new JAXBElement<String>(_KeyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStatusResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "GetStatusResponse")
    public JAXBElement<GetStatusResponseType> createGetStatusResponse(GetStatusResponseType value) {
        return new JAXBElement<GetStatusResponseType>(_GetStatusResponse_QNAME, GetStatusResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCMSSignatureRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "CreateCMSSignatureRequest")
    public JAXBElement<CreateCMSSignatureRequestType> createCreateCMSSignatureRequest(CreateCMSSignatureRequestType value) {
        return new JAXBElement<CreateCMSSignatureRequestType>(_CreateCMSSignatureRequest_QNAME, CreateCMSSignatureRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeyValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "KeyValue")
    public JAXBElement<KeyValueType> createKeyValue(KeyValueType value) {
        return new JAXBElement<KeyValueType>(_KeyValue_QNAME, KeyValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VerifyCMSSignatureResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "VerifyCMSSignatureResponse")
    public JAXBElement<VerifyCMSSignatureResponseType> createVerifyCMSSignatureResponse(VerifyCMSSignatureResponseType value) {
        return new JAXBElement<VerifyCMSSignatureResponseType>(_VerifyCMSSignatureResponse_QNAME, VerifyCMSSignatureResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCMSSignatureResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "CreateCMSSignatureResponse")
    public JAXBElement<CreateCMSSignatureResponseType> createCreateCMSSignatureResponse(CreateCMSSignatureResponseType value) {
        return new JAXBElement<CreateCMSSignatureResponseType>(_CreateCMSSignatureResponse_QNAME, CreateCMSSignatureResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoboxAvailableResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "InfoboxAvailableResponse")
    public JAXBElement<InfoboxAvailableResponseType> createInfoboxAvailableResponse(InfoboxAvailableResponseType value) {
        return new JAXBElement<InfoboxAvailableResponseType>(_InfoboxAvailableResponse_QNAME, InfoboxAvailableResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateXMLSignatureResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "CreateXMLSignatureResponse")
    public JAXBElement<CreateXMLSignatureResponseType> createCreateXMLSignatureResponse(CreateXMLSignatureResponseType value) {
        return new JAXBElement<CreateXMLSignatureResponseType>(_CreateXMLSignatureResponse_QNAME, CreateXMLSignatureResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link X509IssuerSerialType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509IssuerSerial", scope = X509DataType.class)
    public JAXBElement<X509IssuerSerialType> createX509DataTypeX509IssuerSerial(X509IssuerSerialType value) {
        return new JAXBElement<X509IssuerSerialType>(_X509DataTypeX509IssuerSerial_QNAME, X509IssuerSerialType.class, X509DataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509Certificate", scope = X509DataType.class)
    public JAXBElement<byte[]> createX509DataTypeX509Certificate(byte[] value) {
        return new JAXBElement<byte[]>(_X509DataTypeX509Certificate_QNAME, byte[].class, X509DataType.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509SKI", scope = X509DataType.class)
    public JAXBElement<byte[]> createX509DataTypeX509SKI(byte[] value) {
        return new JAXBElement<byte[]>(_X509DataTypeX509SKI_QNAME, byte[].class, X509DataType.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509SubjectName", scope = X509DataType.class)
    public JAXBElement<String> createX509DataTypeX509SubjectName(String value) {
        return new JAXBElement<String>(_X509DataTypeX509SubjectName_QNAME, String.class, X509DataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509CRL", scope = X509DataType.class)
    public JAXBElement<byte[]> createX509DataTypeX509CRL(byte[] value) {
        return new JAXBElement<byte[]>(_X509DataTypeX509CRL_QNAME, byte[].class, X509DataType.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "HMACOutputLength", scope = SignatureMethodType.class)
    public JAXBElement<BigInteger> createSignatureMethodTypeHMACOutputLength(BigInteger value) {
        return new JAXBElement<BigInteger>(_SignatureMethodTypeHMACOutputLength_QNAME, BigInteger.class, SignatureMethodType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SPKISexp", scope = SPKIDataType.class)
    public JAXBElement<byte[]> createSPKIDataTypeSPKISexp(byte[] value) {
        return new JAXBElement<byte[]>(_SPKIDataTypeSPKISexp_QNAME, byte[].class, SPKIDataType.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "PGPKeyID", scope = PGPDataType.class)
    public JAXBElement<byte[]> createPGPDataTypePGPKeyID(byte[] value) {
        return new JAXBElement<byte[]>(_PGPDataTypePGPKeyID_QNAME, byte[].class, PGPDataType.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "PGPKeyPacket", scope = PGPDataType.class)
    public JAXBElement<byte[]> createPGPDataTypePGPKeyPacket(byte[] value) {
        return new JAXBElement<byte[]>(_PGPDataTypePGPKeyPacket_QNAME, byte[].class, PGPDataType.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "FailedReference", scope = ReferencesCheckResultInfoType.class)
    public JAXBElement<BigInteger> createReferencesCheckResultInfoTypeFailedReference(BigInteger value) {
        return new JAXBElement<BigInteger>(_ReferencesCheckResultInfoTypeFailedReference_QNAME, BigInteger.class, ReferencesCheckResultInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "SignatureCheck", scope = VerifyCMSSignatureResponseType.class)
    public JAXBElement<CheckResultType> createVerifyCMSSignatureResponseTypeSignatureCheck(CheckResultType value) {
        return new JAXBElement<CheckResultType>(_VerifyCMSSignatureResponseTypeSignatureCheck_QNAME, CheckResultType.class, VerifyCMSSignatureResponseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "CertificateCheck", scope = VerifyCMSSignatureResponseType.class)
    public JAXBElement<CheckResultType> createVerifyCMSSignatureResponseTypeCertificateCheck(CheckResultType value) {
        return new JAXBElement<CheckResultType>(_VerifyCMSSignatureResponseTypeCertificateCheck_QNAME, CheckResultType.class, VerifyCMSSignatureResponseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeyInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "SignerInfo", scope = VerifyCMSSignatureResponseType.class)
    public JAXBElement<KeyInfoType> createVerifyCMSSignatureResponseTypeSignerInfo(KeyInfoType value) {
        return new JAXBElement<KeyInfoType>(_VerifyCMSSignatureResponseTypeSignerInfo_QNAME, KeyInfoType.class, VerifyCMSSignatureResponseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "ReferringSigReference", scope = ManifestRefsCheckResultInfoType.class)
    public JAXBElement<BigInteger> createManifestRefsCheckResultInfoTypeReferringSigReference(BigInteger value) {
        return new JAXBElement<BigInteger>(_ManifestRefsCheckResultInfoTypeReferringSigReference_QNAME, BigInteger.class, ManifestRefsCheckResultInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.buergerkarte.at/namespaces/securitylayer/1.2#", name = "FailedReference", scope = ManifestRefsCheckResultInfoType.class)
    public JAXBElement<BigInteger> createManifestRefsCheckResultInfoTypeFailedReference(BigInteger value) {
        return new JAXBElement<BigInteger>(_ReferencesCheckResultInfoTypeFailedReference_QNAME, BigInteger.class, ManifestRefsCheckResultInfoType.class, value);
    }

}
