//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 04:01:10 PM CEST 
//


package at.gv.egiz.sl.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XMLToBeEncryptedNewContentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XMLToBeEncryptedNewContentType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.buergerkarte.at/namespaces/securitylayer/1.2#}Base64XMLLocRefContentType">
 *       &lt;attribute name="EncDataReference" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XMLToBeEncryptedNewContentType")
public class XMLToBeEncryptedNewContentType
    extends Base64XMLLocRefContentType
{

    @XmlAttribute(name = "EncDataReference")
    @XmlSchemaType(name = "anyURI")
    protected String encDataReference;

    /**
     * Gets the value of the encDataReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncDataReference() {
        return encDataReference;
    }

    /**
     * Sets the value of the encDataReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncDataReference(String value) {
        this.encDataReference = value;
    }

}
